services:
  piso_wifi:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - WIFI_INTERFACE=eth0
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      - piso_net

networks:
  piso_net:
    driver: bridge